[project]
name = "aws-dbt-snowflake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.5",
    "dbt-snowflake>=1.9.2",
]

[project.scripts]
dbt-snowflake = "dbt_snowflake:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "certifi>=2026.7.22",
]
